### ISSUE TITLE
Upload to LUIS is failing

### ISSUE THREAD

**Issue by chrisvella** [alyssaong1/botframework-smalltalk#3]
When I run `node uploadtoluis.js` I get an error:

```
Unhandled rejection ReferenceError: response is not defined
    at /home/chris/botframework-smalltalk/luis/uploadtoluis.js:64:50
    at tryCatcher (/home/chris/botframework-smalltalk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/chris/botframework-smalltalk/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/chris/botframework-smalltalk/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/chris/botframework-smalltalk/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/chris/botframework-smalltalk/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/chris/botframework-smalltalk/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/chris/botframework-smalltalk/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/chris/botframework-smalltalk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

After removing `response.statusMessage` from line 64, I get the `Web request failed:`

I have filled in all the .env values. I double checked the URL you are building and it seems okay according to the API...

Cheers

**Comment by alyssaong1** [comment]
Make sure you are using the starter key (the one provided when you create the LUIS app). For some reason it only works with the starter key from when I last tried. Let me know how it goes

**Comment by chrisvella** [comment]
Pretty sure I had the correct starter key set, but I will take another look
later.

**Comment by alyssaong1** [comment]
.env file for the LUIS credentials also needs to be inside the Luis folder

**Comment by alyssaong1** [comment]
I’ll have to make an update to reflect this in the repo later. Let me know how this goes.

**Comment by chrisvella** [comment]
I have verified this with fresh eyes. I have the set the app id as the LUIS_APP_ID and the Key String as LUIS_KEY. I still get the same error. Thanks

**Comment by kirsanau** [comment]
had same problem.
to fix
1. move env file to luis folder
2. make sure you set properly version of your luis, e.g. 
LUIS_APP_ID=xxx
LUIS_KEY=xxx
LUIS_VERSION=0.1

**Comment by alyssaong1** [comment]
I have fixed this to reflect in the code, see https://github.com/alyssaong1/botframework-smalltalk/commit/82386d74cbb9fdafd44546141bcd66fcfceb4df4
